version: '3.2'

services:
  malla_front:
    container_name: malla-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NUXT_SESSION_SESSION_STORAGE_OPTIONS_OPTIONS_URL=${NUXT_SESSION_SESSION_STORAGE_OPTIONS_OPTIONS_URL}
    expose:
      - 3223:3223
    ports:
      - 3223:3223
    env_file:
      - .env
    networks:
      - umag_network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.malla_front.entrypoints=web,websecure"
      - "traefik.http.services.malla_front.loadbalancer.server.port=3223"
      - "traefik.http.routers.malla_front.service=malla_front"
      #- "traefik.http.routers.malla_front.middlewares=redirect-to-session@file"
      #LOCAL
      #- "traefik.http.routers.malla_front.rule=Host(`frontend.localhost`) && (PathPrefix(`/mallas`) || PathPrefix(`/api/mallas/session`))"      
      #- "traefik.http.routers.malla_front.tls=false"
      #PROD
      - "traefik.http.routers.malla_front.rule=Host(`pichimalen.org`) && (PathPrefix(`/mallas`) || PathPrefix(`/api/mallas/session`))"      
      - "traefik.http.routers.malla_front.tls=true"
networks:
  umag_network:
    external: true